name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "14"
          remove_duplicates: true
          feed_list: "https://medium.com/feed/@saurabhkashyap0001,https://dev.to/feed/n8n,https://medium.com/feed/@harshil1712"
